<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

class Book extends Model
{
    use HasFactory;

    protected $fillable = [
        'title'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($book) {
            $book->pages->each(fn ($page) => $page->delete());
            Storage::disk('public')->deleteDirectory($book->path);
        });
    }

    protected function title(): Attribute
    {
        return Attribute::make(
            get: fn($value) => ucwords($value),
            set: fn($value) => strtolower($value)
        );
    }

    protected function folderName(): Attribute
    {
        return Attribute::get(fn() => str($this->title)->ascii()->lower()->replaceMatches("/([^\p{L}\s\d\-_~,;:\[\]\(\).'])/", '')->snake()->value());
    }

    protected function path(): Attribute
    {
        return Attribute::get(fn() => 'books/' . $this->folderName);
    }

    protected function coverPath(): Attribute
    {
        $storage = Storage::disk('public');
        $coverPath = $this->path . '/cover.jpg';
        if (!$storage->exists($coverPath)) {
            $pages = collect($storage->files($this->path . '/pages'));
            $firstPage = $pages->sort()->first();
            if ($firstPage) {
                $storage->copy($firstPage, $coverPath);
            }
        }
        return Attribute::get(fn() => $coverPath);
    }

    protected function coverUrl(): Attribute
    {
        return Attribute::get(fn() => Storage::url($this->coverPath));
    }

    protected function cover300Path(): Attribute
    {
        return Attribute::get(function () {
            $cover300Path = "{$this->path}/cover-300.jpg";
            $publicDisk = Storage::disk('public');
            if (!$publicDisk->exists($cover300Path)) {
                $cover = imagecreatefromstring($publicDisk->get($this->coverPath));
                $cover300 = imagescale($cover, 300);
                $publicDisk->put($cover300Path, '');
                imagejpeg($cover300, $publicDisk->path($cover300Path));
            }
            return $cover300Path;
        });
    }

    protected function cover300Url(): Attribute
    {
        return Attribute::get(fn() => \Storage::disk('public')->url($this->cover300Path));
    }

    public function pages(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Page::class);
    }

    public function storeCover(UploadedFile $file): void
    {
        $file->storeAs('books/' . $this->folderName, 'cover.jpg', 'public');
    }
}
